# Generated by Django 4.0.6 on 2022-07-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_product', models.CharField(max_length=50, verbose_name='тип товара')),
                ('date_delivery', models.CharField(max_length=50, verbose_name='дата доставки')),
                ('image', models.ImageField(upload_to='', verbose_name='изображение товара')),
                ('point', models.JSONField(verbose_name='адреса доставки')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата создания товара')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['type_product'],
            },
        ),
    ]
