# Generated by Django 4.0.6 on 2022-07-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_delivery',
            field=models.DateField(verbose_name='дата доставки'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='point',
        ),
        migrations.AddField(
            model_name='product',
            name='point',
            field=models.ManyToManyField(to='product.product', verbose_name='адреса доставки'),
        ),
    ]
