# Generated by Django 4.0.6 on 2022-07-20 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_date_delivery_remove_product_point_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='point',
        ),
        migrations.AddField(
            model_name='product',
            name='point',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='адреса доставки'),
            preserve_default=False,
        ),
    ]
