# Generated by Django 4.0.6 on 2022-07-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_point_product_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='point',
        ),
        migrations.AddField(
            model_name='product',
            name='point',
            field=models.ManyToManyField(to='product.product', verbose_name='адреса доставки'),
        ),
    ]
