# Generated by Django 4.0.6 on 2022-07-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='point_2',
            field=models.JSONField(default=dict, verbose_name='адреса доставки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='point',
            field=models.CharField(default=dict, max_length=50, verbose_name='адреса доставки'),
        ),
    ]
