# Generated by Django 4.0.6 on 2022-07-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_point_2_alter_product_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='point_2',
            field=models.JSONField(null=True, verbose_name='адреса доставки'),
        ),
    ]
