# Generated by Django 4.0.6 on 2022-07-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_point_alter_product_point_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_delivery',
            field=models.DateField(blank=True, null=True, verbose_name='дата доставки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_product',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='тип товара'),
        ),
    ]
