# Generated by Django 4.0.6 on 2022-07-28 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_date_delivery_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
    ]
